image:
  name: hashicorp/terraform:latest
  entrypoint:
    - /usr/bin/env
    - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

cache:
  key: terraform
  paths:
    - ${CI_PROJECT_DIR}/src/.terraform
    
before_script:
  - cd ${CI_PROJECT_DIR}/src
  - rm -rf .terraform
  - terraform --version

stages:
  - prepare
  - validate
  - plan
  - deploy

init:
  stage: prepare
  script:
    - gitlab-terraform init

validate:
  stage: validate
  script:
    - gitlab-terraform validate

plan:
  stage: plan
  script:
    - terraform plan -out "planfile"
  dependencies:
    - validate
  artifacts:
    paths:
      - planfile


apply:
  stage: deploy
  environment:
    name: development
  script:
    - gitlab-terraform apply
  dependencies:
    - plan
  when: manual
  only:
    - master